### ISSUE TITLE
centos 8 no systemd-python

### ISSUE THREAD

**Issue by aboe76** [saltstack-formulas/systemd-formula#52]
Centos 8 has python3-systemd

**Comment by myii** [comment]
@aboe76 We'll be getting `centos-8` pre-salted images soon, thanks to @javierbertoli.  That will help manage issues like this.

**Comment by aboe76** [comment]
@myii no problem just upgraded my home setup with one machine to centos 8
found out the new salt version has an ipv6 dns bug...and some formulas needs some love..
thank god it's weekend !!!.
