### ISSUE TITLE
[FEATURE] manage systemd overrides

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/systemd-formula#61]
### Describe the solution you'd like

A way to manage systemd overrides in pillar.

**Comment by kti-curtis** [comment]
`dropin: true` creates a salt-override.conf file and reloads systemd  --> good

But if you want to override an existing entry, you need two entries.  For example, if you're overriding `ExecStart`   First a blank row that clears it followed by your override.  (what an odd override system...)

```
ExecStart=
ExecStart= myapp -d
```

caveat: `Type: simple` can only have one ExecStart line and requires the above.  `Type: oneshot` can have multiple `ExecStart` and they are executed in series.
